name: CI

on:
  push:
    paths:
      - "data.json"
      - "script/check.sh"
    branches: [ "master" ]
  pull_request:
    paths:
      - "data.json"
      - "script/check.sh"
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Automated check
        run: $GITHUB_WORKSPACE/script/check.sh
